services:
  node2:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "SRV"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.2"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.2
    volumes:
      - ./bin/bin_op:/app/binary

  node3:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "SRV"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.3"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.3
    volumes:
      - ./bin/bin_op:/app/binary

  node4:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "SRV"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.4"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.4
    volumes:
      - ./bin/bin_op:/app/binary

networks:
  raft_no_dyno_cc:
    driver: bridge
    ipam:
      config:
        - subnet: 171.10.0.0/24
