

services:
  node6:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "SRV"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.6"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.6
    volumes:
      - ./bin/bin_op:/app/binary



  node4:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "SRV"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.4"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.4
    volumes:
      - ./bin/bin_op:/app/binary

  node5:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "SRV"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.5"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.5
    volumes:
      - ./bin/bin_op:/app/binary

  cilent:
    image: raft/no_dyno_cc:latest
    environment:
      ROLE: "CLIENT"
      NODES: ${RAFT_REPLICAS} 
      ID: "171.10.0.9"
    networks:
      raft_no_dyno_cc:
        ipv4_address: 171.10.0.9
    volumes:
      - ./bin/bin_op:/app/binary


networks:
  raft_no_dyno_cc:
    driver: bridge
    ipam:
      config:
        - subnet: 171.10.0.0/24
